// Code generated by protoc-gen-gogo.
// source: signal_process.proto
// DO NOT EDIT!

package garden

import proto "code.google.com/p/gogoprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type SignalProcessRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	ProcessId        *uint32 `protobuf:"varint,2,req,name=process_id" json:"process_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SignalProcessRequest) Reset()         { *m = SignalProcessRequest{} }
func (m *SignalProcessRequest) String() string { return proto.CompactTextString(m) }
func (*SignalProcessRequest) ProtoMessage()    {}

func (m *SignalProcessRequest) GetHandle() string {
	if m != nil && m.Handle != nil {
		return *m.Handle
	}
	return ""
}

func (m *SignalProcessRequest) GetProcessId() uint32 {
	if m != nil && m.ProcessId != nil {
		return *m.ProcessId
	}
	return 0
}

type SignalProcessResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SignalProcessResponse) Reset()         { *m = SignalProcessResponse{} }
func (m *SignalProcessResponse) String() string { return proto.CompactTextString(m) }
func (*SignalProcessResponse) ProtoMessage()    {}

func init() {
}
